using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace SquadDash;

/// <summary>
/// Fields the AI sends when emitting an INBOX_MESSAGE_JSON block.
/// Timestamp, Id, and Read are generated by the host, not the AI.
/// </summary>
internal sealed class InboxMessageDto
{
    [JsonPropertyName("subject")]
    public string Subject { get; init; } = string.Empty;

    [JsonPropertyName("from")]
    public string From { get; init; } = string.Empty;

    [JsonPropertyName("body")]
    public string Body { get; init; } = string.Empty;

    [JsonPropertyName("attachments")]
    public IReadOnlyList<InboxAttachment> Attachments { get; init; } = [];

    [JsonPropertyName("actions")]
    public IReadOnlyList<InboxAction> Actions { get; init; } = [];

    [JsonPropertyName("priority")]
    public string? Priority { get; init; }
}

/// <summary>
/// Detects and extracts <c>INBOX_MESSAGE_JSON:</c> sentinel blocks from AI responses.
/// Uses the same structural pattern as <see cref="HostCommandParser"/>.
/// </summary>
internal static class InboxMessageParser
{
    private const string Marker = "INBOX_MESSAGE_JSON:";

    private enum JsonStringRole
    {
        PropertyName,
        Value,
    }

    private static readonly JsonSerializerOptions ParseOptions = new()
    {
        PropertyNameCaseInsensitive = true,
    };

    /// <summary>
    /// Attempts to extract an INBOX_MESSAGE_JSON block from <paramref name="text"/>.
    /// Returns true when the sentinel is found and the JSON is valid.
    /// <paramref name="body"/> receives the visible text with the block removed (trimmed);
    /// <paramref name="dto"/> receives the parsed payload.
    /// Tolerates arbitrary prose appearing after the closing brace.
    /// When multiple markers are present the last one is used.
    /// </summary>
    internal static bool TryExtract(string text, out string body, out InboxMessageDto? dto)
    {
        var result = TryExtract(text, out var extraction);
        if (result && extraction is not null)
        {
            body = extraction.VisibleText;
            dto  = extraction.Message;
            return true;
        }

        body = text;
        dto  = null;
        return false;
    }

    /// <summary>
    /// Attempts to extract an INBOX_MESSAGE_JSON block and returns structured details about
    /// the visible text before and after the machine-readable payload.
    /// </summary>
    internal static bool TryExtract(string text, out InboxMessageExtraction? extraction)
    {
        extraction = null;

        if (string.IsNullOrWhiteSpace(text))
            return false;

        var normalized = text.Replace("\r\n", "\n").Replace('\r', '\n');

        // Use the last occurrence so that multiple blocks resolve to the final one.
        int markerIdx = normalized.LastIndexOf(Marker, StringComparison.Ordinal);
        if (markerIdx < 0)
            return false;

        int braceStart = normalized.IndexOf('{', markerIdx + Marker.Length);
        if (braceStart < 0)
            return false;

        int braceEnd = -1;
        var containers = new List<char>();
        bool inString = false;
        bool escaped  = false;
        var stringRole = JsonStringRole.Value;
        for (int i = braceStart; i < normalized.Length; i++)
        {
            char c = normalized[i];
            if (escaped)
            {
                escaped = false;
                continue;
            }
            if (c == '\\' && inString) { escaped = true; continue; }
            if (c == '"')
            {
                if (!inString)
                {
                    stringRole = DetermineStringRole(normalized, i, containers);
                    inString = true;
                }
                else if (IsLikelyJsonStringTerminator(normalized, i, stringRole, containers))
                {
                    inString = false;
                }
                continue;
            }
            if (inString) continue;

            if (c == '{' || c == '[')
            {
                containers.Add(c);
                continue;
            }

            if (c == '}' || c == ']')
            {
                if (containers.Count == 0 || !DoesCloseContainer(containers[^1], c))
                    return false;

                containers.RemoveAt(containers.Count - 1);
                if (containers.Count == 0 && c == '}') { braceEnd = i; break; }
            }
        }

        if (braceEnd < 0)
            return false;

        var jsonText = normalized[braceStart..(braceEnd + 1)];

        try
        {
            var sanitized = SanitizeMalformedStringContent(jsonText);
            var dto = JsonSerializer.Deserialize<InboxMessageDto>(sanitized, ParseOptions);
            if (dto is null)
                return false;

            dto = StripNoOpDoneActions(dto);
            var before = StripTrailingCodeFence(normalized[..markerIdx].TrimEnd());
            var after  = StripLeadingCodeFence(normalized[(braceEnd + 1)..]).Trim();
            extraction = new InboxMessageExtraction(
                Message:           dto,
                VisibleText:       CombineVisibleText(before, after),
                TextBeforeBlock:   before,
                TrailingText:      after,
                MarkerIndex:       markerIdx,
                JsonStartIndex:    braceStart,
                JsonEndIndex:      braceEnd);
            return true;
        }
        catch (JsonException)
        {
            return false;
        }
    }

    internal static bool TryParseJsonObject(string jsonText, out InboxMessageDto? dto)
    {
        dto = null;
        if (string.IsNullOrWhiteSpace(jsonText))
            return false;

        try
        {
            var sanitized = SanitizeMalformedStringContent(jsonText.Replace("\r\n", "\n").Replace('\r', '\n'));
            dto = JsonSerializer.Deserialize<InboxMessageDto>(sanitized, ParseOptions);
            if (dto is null)
                return false;

            dto = StripNoOpDoneActions(dto);
            return true;
        }
        catch (JsonException)
        {
            dto = null;
            return false;
        }
    }

    private static string CombineVisibleText(string before, string after)
    {
        if (string.IsNullOrWhiteSpace(before))
            return after.Trim();
        if (string.IsNullOrWhiteSpace(after))
            return before.TrimEnd();
        return before.TrimEnd() + "\n\n" + after.Trim();
    }

    /// <summary>
    /// Replaces common malformed content inside JSON string values with valid escape
    /// sequences. The AI sometimes emits multi-line prompt text with real newlines
    /// rather than \n, or prose quotes rather than \", which makes the JSON invalid.
    /// Also fixes invalid escape sequences (e.g. \d → \\d) and strips C0 control chars.
    /// </summary>
    internal static string SanitizeMalformedStringContent(string json)
    {
        var sb = new System.Text.StringBuilder(json.Length + 64);
        bool inString = false;
        var containers = new List<char>();
        var stringRole = JsonStringRole.Value;
        for (int i = 0; i < json.Length; i++)
        {
            char c = json[i];
            if (c == '\\' && inString)
            {
                if (i + 1 < json.Length)
                {
                    char next = json[i + 1];
                    if (next == '"' || next == '\\' || next == '/' ||
                        next == 'b' || next == 'f'  || next == 'n' ||
                        next == 'r' || next == 't'  || next == 'u')
                    {
                        // Valid JSON escape — emit as-is and consume both chars.
                        sb.Append('\\');
                        sb.Append(next);
                        i++;
                    }
                    else
                    {
                        // Invalid escape (e.g. \d, \p) — double the backslash so
                        // the sequence becomes valid JSON string content.
                        sb.Append('\\');
                        sb.Append('\\');
                        sb.Append(next);
                        i++;
                    }
                }
                else
                {
                    // Trailing backslash at end of input — escape it.
                    sb.Append('\\');
                    sb.Append('\\');
                }
                continue;
            }
            if (c == '"')
            {
                if (!inString)
                {
                    stringRole = DetermineStringRole(json, i, containers);
                    inString = true;
                    sb.Append(c);
                }
                else if (IsLikelyJsonStringTerminator(json, i, stringRole, containers))
                {
                    inString = false;
                    sb.Append(c);
                }
                else
                {
                    sb.Append("\\\"");
                }
                continue;
            }
            if (inString)
            {
                if (c == '\r')
                {
                    // Collapse \r\n → \\n, bare \r → \\n
                    if (i + 1 < json.Length && json[i + 1] == '\n') i++;
                    sb.Append("\\n");
                    continue;
                }
                if (c == '\n') { sb.Append("\\n"); continue; }
                if (c == '\t') { sb.Append("\\t"); continue; }
                if (c < ' ')  { continue; }  // strip other C0 control chars (U+0001–U+001F)
            }
            else
            {
                if (c == '{' || c == '[')
                    containers.Add(c);
                else if ((c == '}' || c == ']') &&
                         containers.Count > 0 &&
                         DoesCloseContainer(containers[^1], c))
                    containers.RemoveAt(containers.Count - 1);
            }
            sb.Append(c);
        }
        return sb.ToString();
    }

    private static JsonStringRole DetermineStringRole(
        string json,
        int quoteIndex,
        IReadOnlyList<char> containers)
    {
        var previous = PreviousNonWhitespace(json, quoteIndex);
        if (previous == ':')
            return JsonStringRole.Value;

        if (containers.Count > 0 &&
            containers[containers.Count - 1] == '{' &&
            (previous == '{' || previous == ','))
            return JsonStringRole.PropertyName;

        return JsonStringRole.Value;
    }

    private static char PreviousNonWhitespace(string json, int quoteIndex)
    {
        for (int i = quoteIndex - 1; i >= 0; i--)
        {
            var c = json[i];
            if (!char.IsWhiteSpace(c))
                return c;
        }

        return '\0';
    }

    private static bool IsLikelyJsonStringTerminator(
        string json,
        int quoteIndex,
        JsonStringRole role,
        IReadOnlyList<char> containers)
    {
        if (!TryGetNextNonWhitespace(json, quoteIndex, out var nextIndex, out var next))
            return true;

        if (role == JsonStringRole.PropertyName)
            return next == ':';

        return next switch
        {
            ':' => false,
            ',' => IsLikelyCommaAfterValue(json, nextIndex, containers),
            '}' or ']' => IsLikelyCloseAfterValue(json, nextIndex, containers),
            _ => false,
        };
    }

    private static bool TryGetNextNonWhitespace(string json, int index, out int nextIndex, out char next)
    {
        for (int i = index + 1; i < json.Length; i++)
        {
            var c = json[i];
            if (char.IsWhiteSpace(c))
                continue;

            nextIndex = i;
            next = c;
            return true;
        }

        nextIndex = -1;
        next = '\0';
        return false;
    }

    private static bool IsLikelyCommaAfterValue(
        string json,
        int commaIndex,
        IReadOnlyList<char> containers)
    {
        if (!TryGetNextNonWhitespace(json, commaIndex, out _, out var afterComma))
            return false;

        if (containers.Count == 0)
            return false;

        return containers[containers.Count - 1] switch
        {
            '{' => afterComma == '"',
            '[' => IsLikelyJsonValueStart(afterComma),
            _ => false,
        };
    }

    private static bool IsLikelyCloseAfterValue(
        string json,
        int closeIndex,
        IReadOnlyList<char> containers)
    {
        if (containers.Count == 0 || !DoesCloseContainer(containers[containers.Count - 1], json[closeIndex]))
            return false;

        if (!TryGetNextNonWhitespace(json, closeIndex, out _, out var afterClose))
            return true;

        return afterClose is ',' or '}' or ']' ||
               containers.Count == 1;
    }

    private static bool IsLikelyJsonValueStart(char c) =>
        c == '"' ||
        c == '{' ||
        c == '[' ||
        c == '-' ||
        c is >= '0' and <= '9' ||
        c == 't' ||
        c == 'f' ||
        c == 'n';

    private static bool DoesCloseContainer(char open, char close) =>
        (open == '{' && close == '}') ||
        (open == '[' && close == ']');

    /// <summary>
    /// Strips 'done' actions whose labels are purely acknowledgement-only (e.g. Dismiss, OK, Close).
    /// These add no value — clicking them records nothing and can't launch any agent.
    /// </summary>
    private static readonly System.Collections.Generic.HashSet<string> NoOpDoneLabels =
        new(System.StringComparer.OrdinalIgnoreCase)
        {
            "dismiss", "ok", "okay", "close", "cancel", "got it", "done",
            "acknowledge", "acknowledged", "clear", "ignore", "never mind",
            "no thanks", "not now", "skip"
        };

    private static InboxMessageDto StripNoOpDoneActions(InboxMessageDto dto)
    {
        if (dto.Actions.Count == 0)
            return dto;

        var filtered = new System.Collections.Generic.List<InboxAction>(dto.Actions.Count);
        foreach (var action in dto.Actions)
        {
            bool isNoOp = string.Equals(action.RouteMode, "done", System.StringComparison.OrdinalIgnoreCase)
                       && NoOpDoneLabels.Contains(action.Label.Trim());
            if (!isNoOp)
                filtered.Add(action);
        }

        if (filtered.Count == dto.Actions.Count)
            return dto;

        return new InboxMessageDto
        {
            Subject     = dto.Subject,
            From        = dto.From,
            Body        = dto.Body,
            Attachments = dto.Attachments,
            Actions     = filtered,
            Priority    = dto.Priority,
        };
    }

    /// <summary>
    /// Strips a trailing code-fence opening line (``` or ```lang) if present,
    /// so that <c>body</c> does not contain the fence that wraps the INBOX block.
    /// </summary>
    private static string StripTrailingCodeFence(string text)
    {
        if (text.Length == 0)
            return text;

        int lastNewline = text.LastIndexOf('\n');
        var lastLine    = lastNewline < 0 ? text : text[(lastNewline + 1)..];
        var trimmed     = lastLine.TrimStart();
        if (trimmed.StartsWith("```", StringComparison.Ordinal))
        {
            var before = lastNewline < 0 ? string.Empty : text[..lastNewline];
            return before.TrimEnd();
        }
        return text;
    }

    private static string StripLeadingCodeFence(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
            return string.Empty;

        var trimmed = text.TrimStart();
        if (!trimmed.StartsWith("```", StringComparison.Ordinal))
            return text;

        var lineEnd = trimmed.IndexOf('\n');
        if (lineEnd < 0)
            return string.Empty;

        return trimmed[(lineEnd + 1)..];
    }
}

internal sealed record InboxMessageExtraction(
    InboxMessageDto Message,
    string VisibleText,
    string TextBeforeBlock,
    string TrailingText,
    int MarkerIndex,
    int JsonStartIndex,
    int JsonEndIndex);
